In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
domestic_consumption = "Domestic-consumption.csv"
domestic_consumption_df = pd.read_csv(domestic_consumption)
domestic_consumption_df

,Domestic consumption by all exporting countries,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,In thousand 60kg bags,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Crop year,NaN,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,April group,NaN,"10,408","10,708","11,212","11,453","11,506","12,334","13,236","13,805",...,"22,695","23,439","24,346","25,171","25,263","25,659","25,948","26,757","27,636","27,950"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
domestic_consumption_df.dropna(subset=["Domestic consumption by all exporting countries"], how="all", inplace=True)
domestic_consumption_df

,Domestic consumption by all exporting countries,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,In thousand 60kg bags,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Crop year,NaN,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19
4,April group,NaN,"10,408","10,708","11,212","11,453","11,506","12,334","13,236","13,805",...,"22,695","23,439","24,346","25,171","25,263","25,659","25,948","26,757","27,636","27,950"
5,Angola,(R/A),20,30,35,20,25,10,20,40,...,30,30,30,30,30,30,30,30,30,30
6,Bolivia (Plurinational State of),(A),25,27,28,29,30,31,32,33,...,46,48,49,51,52,54,55,57,59,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,Venezuela,(A),782,815,850,886,923,962,"1,003","1,046",...,"1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,600","1,550"
63,Viet Nam,(R/A),150,230,250,267,267,282,298,314,...,"1,208","1,583","1,650","1,825","2,000","2,200","2,300","2,400","2,500","2,700"
64,Yemen,(A),0,0,0,0,0,0,0,0,...,130,130,130,130,130,125,115,100,90,65
66,Total,NaN,"19,509","20,228","20,951","21,098","21,360","22,603","23,513","24,271",...,"40,310","42,208","43,690","44,754","45,509","46,666","47,548","48,488","49,793","50,510"
67,Â© International Coffee Organization,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
new_dc_df = domestic_consumption_df.drop(index=[0, 4, 20, 29, 66, 67])
new_dc_df

,Domestic consumption by all exporting countries,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
2,Crop year,NaN,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19
5,Angola,(R/A),20,30,35,20,25,10,20,40,...,30,30,30,30,30,30,30,30,30,30
6,Bolivia (Plurinational State of),(A),25,27,28,29,30,31,32,33,...,46,48,49,51,52,54,55,57,59,60
7,Brazil,(A/R),"8,200","8,500","8,900","9,100","9,300","10,100","11,000","11,500",...,"18,390","19,132","19,720","20,330","20,085","20,333","20,508","21,225","21,997","22,250"
8,Burundi,(A/R),2,2,2,2,2,2,2,2,...,1,2,2,2,2,2,2,2,2,2
9,Ecuador,(A/R),350,350,350,350,350,350,300,300,...,150,150,150,150,155,155,155,155,155,155
10,Indonesia,(R/A),"1,242","1,280","1,319","1,359","1,400","1,443","1,486","1,532",...,"3,333","3,333","3,667","3,900","4,250","4,417","4,550","4,650","4,750","4,800"
11,Madagascar,(R),350,300,350,360,167,167,167,167,...,467,467,450,430,410,390,370,360,365,375
12,Malawi,(A),2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
13,Papua New Guinea,(A/R),3,3,3,2,2,2,2,2,...,2,1,1,2,2,2,2,2,2,2
14,Paraguay,(A),15,15,15,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
15,Peru,(A),190,190,200,200,200,200,200,200,...,250,250,250,250,250,250,250,250,250,250
16,Rwanda,(A),1,1,1,1,1,1,1,3,...,1,1,1,1,1,1,1,1,1,1
17,Timor-Leste,(A),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,Zimbabwe,(A),8,8,8,8,8,7,4,4,...,4,4,4,4,4,4,4,4,4,4
21,Congo,(R),3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
22,Cuba,(A),213,213,195,194,194,194,189,195,...,220,220,220,220,220,220,220,220,220,220
23,Dominican Republic,(A/R),320,320,320,320,330,350,325,325,...,378,378,378,378,383,388,388,390,390,390
24,Haiti,(A),220,330,330,330,330,330,330,330,...,340,340,340,340,340,340,340,340,340,345
25,Philippines,(R/A),720,750,750,770,790,810,831,853,...,"1,820","2,125","2,175","2,325","2,550","2,800","3,000","3,030","3,180","3,300"
26,Tanzania,(A/R),4,4,19,18,18,14,17,17,...,47,47,59,72,73,77,92,91,92,92
27,Zambia,(A),2,2,1,1,2,1,1,1,...,0,0,0,0,0,0,0,0,0,0
30,Benin,(R),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,Cameroon,(R/A),83,83,83,100,100,100,100,100,...,69,68,70,72,73,75,76,77,78,78
32,Central African Republic,(R),28,28,28,25,15,10,10,10,...,8,10,13,17,20,20,20,20,20,20
33,Colombia,(A),"1,235","1,269","1,303","1,339","1,375","1,359","1,343","1,328",...,"1,274","1,311","1,435","1,514","1,617","1,665","1,720","1,736","1,793","1,791"
34,Costa Rica,(A),375,375,375,375,375,375,375,375,...,295,407,381,423,335,381,449,329,353,365
35,CÃ´te d'Ivoire,(R),50,50,50,50,50,50,50,50,...,317,317,317,317,317,317,317,317,317,317
36,Democratic Republic of Congo,(R/A),200,200,200,200,200,200,200,200,...,200,200,200,200,200,200,200,200,200,200
37,El Salvador,(A),180,180,230,230,230,270,230,192,...,268,276,273,277,275,280,285,292,300,300
38,Equatorial Guinea,(R),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,Ethiopia,(A),"1,200","1,264","1,331","1,402","1,476","1,555","1,637","1,724",...,"3,210","3,383","3,383","3,400","3,550","3,625","3,700","3,725","3,750","3,800"
40,Gabon,(R),2,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
41,Ghana,(R),17,17,17,17,28,28,3,3,...,2,2,2,2,2,2,2,2,2,2
42,Guatemala,(A/R),300,300,300,310,310,310,300,300,...,320,340,350,360,370,380,390,390,395,395
43,Guinea,(R),25,25,63,33,50,50,50,50,...,50,50,50,50,50,50,50,50,50,50
44,Guyana,(R),0,0,0,0,0,0,0,0,...,8,9,9,9,9,9,9,9,9,9
45,Honduras,(A),188,257,240,230,253,161,168,161,...,307,335,340,345,350,355,365,370,375,375
46,India,(R/A),903,917,917,833,835,837,838,839,...,"1,325","1,325","1,325","1,375","1,400","1,430","1,450","1,440","1,470","1,475"
47,Jamaica,(A),7,11,6,10,15,15,18,20,...,9,9,9,9,9,9,9,9,9,9
48,Kenya,(A),50,50,50,50,50,50,50,50,...,50,50,50,50,55,55,60,60,65,70
49,Lao People's Democratic Republic,(R),0,0,0,0,0,0,0,0,...,150,150,150,150,150,150,150,150,155,155
50,Liberia,(R),3,3,3,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
51,Mexico,(A/R),"1,374","1,200","1,300","1,070","1,020","1,179","1,235","1,201",...,"2,200","2,354","2,354","2,354","2,321","2,347","2,329","2,360","2,400","2,450"
52,Nepal,(A),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53,Nicaragua,(A),34,138,66,109,90,112,95,123,...,197,203,205,208,210,212,214,217,218,220
54,Nigeria,(R),28,36,36,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
55,Panama,(A),63,67,67,67,77,77,77,81,...,67,67,67,67,67,67,67,67,67,67
56,Sierra Leone,(R),9,9,9,5,5,8,8,5,...,5,5,5,5,5,5,5,5,5,5
57,Sri Lanka,(R/A),67,67,28,20,20,20,20,20,...,30,35,35,35,35,35,35,35,35,35
58,Thailand,(R/A),188,220,233,250,283,417,333,390,...,700,775,"1,100","1,130","1,200","1,250","1,300","1,350","1,375","1,400"
59,Togo,(R),1,1,1,1,1,1,1,1,...,2,2,0,0,0,0,0,0,0,0
60,Trinidad & Tobago,(R),8,12,10,10,14,14,14,14,...,11,10,10,10,10,10,10,10,10,10
61,Uganda,(R/A),70,75,75,75,80,80,80,101,...,189,204,210,216,221,229,234,240,245,250
62,Venezuela,(A),782,815,850,886,923,962,"1,003","1,046",...,"1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,600","1,550"
63,Viet Nam,(R/A),150,230,250,267,267,282,298,314,...,"1,208","1,583","1,650","1,825","2,000","2,200","2,300","2,400","2,500","2,700"
64,Yemen,(A),0,0,0,0,0,0,0,0,...,130,130,130,130,130,125,115,100,90,65

In [5]:
new_dc_df.columns = new_dc_df.iloc[0]

In [6]:
new_dc_df.head()

2,Crop year,NaN,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19
2,Crop year,NaN,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19
5,Angola,(R/A),20,30,35,20,25,10,20,40,...,30,30,30,30,30,30,30,30,30,30
6,Bolivia (Plurinational State of),(A),25,27,28,29,30,31,32,33,...,46,48,49,51,52,54,55,57,59,60
7,Brazil,(A/R),"8,200","8,500","8,900","9,100","9,300","10,100","11,000","11,500",...,"18,390","19,132","19,720","20,330","20,085","20,333","20,508","21,225","21,997","22,250"
8,Burundi,(A/R),2,2,2,2,2,2,2,2,...,1,2,2,2,2,2,2,2,2,2

In [7]:
new_dc_df = new_dc_df.drop(2)
new_dc_df.reset_index(drop=True)

2,Crop year,NaN,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19
0,Angola,(R/A),20,30,35,20,25,10,20,40,...,30,30,30,30,30,30,30,30,30,30
1,Bolivia (Plurinational State of),(A),25,27,28,29,30,31,32,33,...,46,48,49,51,52,54,55,57,59,60
2,Brazil,(A/R),"8,200","8,500","8,900","9,100","9,300","10,100","11,000","11,500",...,"18,390","19,132","19,720","20,330","20,085","20,333","20,508","21,225","21,997","22,250"
3,Burundi,(A/R),2,2,2,2,2,2,2,2,...,1,2,2,2,2,2,2,2,2,2
4,Ecuador,(A/R),350,350,350,350,350,350,300,300,...,150,150,150,150,155,155,155,155,155,155
5,Indonesia,(R/A),"1,242","1,280","1,319","1,359","1,400","1,443","1,486","1,532",...,"3,333","3,333","3,667","3,900","4,250","4,417","4,550","4,650","4,750","4,800"
6,Madagascar,(R),350,300,350,360,167,167,167,167,...,467,467,450,430,410,390,370,360,365,375
7,Malawi,(A),2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
8,Papua New Guinea,(A/R),3,3,3,2,2,2,2,2,...,2,1,1,2,2,2,2,2,2,2
9,Paraguay,(A),15,15,15,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
10,Peru,(A),190,190,200,200,200,200,200,200,...,250,250,250,250,250,250,250,250,250,250
11,Rwanda,(A),1,1,1,1,1,1,1,3,...,1,1,1,1,1,1,1,1,1,1
12,Timor-Leste,(A),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,Zimbabwe,(A),8,8,8,8,8,7,4,4,...,4,4,4,4,4,4,4,4,4,4
14,Congo,(R),3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
15,Cuba,(A),213,213,195,194,194,194,189,195,...,220,220,220,220,220,220,220,220,220,220
16,Dominican Republic,(A/R),320,320,320,320,330,350,325,325,...,378,378,378,378,383,388,388,390,390,390
17,Haiti,(A),220,330,330,330,330,330,330,330,...,340,340,340,340,340,340,340,340,340,345
18,Philippines,(R/A),720,750,750,770,790,810,831,853,...,"1,820","2,125","2,175","2,325","2,550","2,800","3,000","3,030","3,180","3,300"
19,Tanzania,(A/R),4,4,19,18,18,14,17,17,...,47,47,59,72,73,77,92,91,92,92
20,Zambia,(A),2,2,1,1,2,1,1,1,...,0,0,0,0,0,0,0,0,0,0
21,Benin,(R),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,Cameroon,(R/A),83,83,83,100,100,100,100,100,...,69,68,70,72,73,75,76,77,78,78
23,Central African Republic,(R),28,28,28,25,15,10,10,10,...,8,10,13,17,20,20,20,20,20,20
24,Colombia,(A),"1,235","1,269","1,303","1,339","1,375","1,359","1,343","1,328",...,"1,274","1,311","1,435","1,514","1,617","1,665","1,720","1,736","1,793","1,791"
25,Costa Rica,(A),375,375,375,375,375,375,375,375,...,295,407,381,423,335,381,449,329,353,365
26,CÃ´te d'Ivoire,(R),50,50,50,50,50,50,50,50,...,317,317,317,317,317,317,317,317,317,317
27,Democratic Republic of Congo,(R/A),200,200,200,200,200,200,200,200,...,200,200,200,200,200,200,200,200,200,200
28,El Salvador,(A),180,180,230,230,230,270,230,192,...,268,276,273,277,275,280,285,292,300,300
29,Equatorial Guinea,(R),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,Ethiopia,(A),"1,200","1,264","1,331","1,402","1,476","1,555","1,637","1,724",...,"3,210","3,383","3,383","3,400","3,550","3,625","3,700","3,725","3,750","3,800"
31,Gabon,(R),2,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
32,Ghana,(R),17,17,17,17,28,28,3,3,...,2,2,2,2,2,2,2,2,2,2
33,Guatemala,(A/R),300,300,300,310,310,310,300,300,...,320,340,350,360,370,380,390,390,395,395
34,Guinea,(R),25,25,63,33,50,50,50,50,...,50,50,50,50,50,50,50,50,50,50
35,Guyana,(R),0,0,0,0,0,0,0,0,...,8,9,9,9,9,9,9,9,9,9
36,Honduras,(A),188,257,240,230,253,161,168,161,...,307,335,340,345,350,355,365,370,375,375
37,India,(R/A),903,917,917,833,835,837,838,839,...,"1,325","1,325","1,325","1,375","1,400","1,430","1,450","1,440","1,470","1,475"
38,Jamaica,(A),7,11,6,10,15,15,18,20,...,9,9,9,9,9,9,9,9,9,9
39,Kenya,(A),50,50,50,50,50,50,50,50,...,50,50,50,50,55,55,60,60,65,70
40,Lao People's Democratic Republic,(R),0,0,0,0,0,0,0,0,...,150,150,150,150,150,150,150,150,155,155
41,Liberia,(R),3,3,3,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
42,Mexico,(A/R),"1,374","1,200","1,300","1,070","1,020","1,179","1,235","1,201",...,"2,200","2,354","2,354","2,354","2,321","2,347","2,329","2,360","2,400","2,450"
43,Nepal,(A),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,Nicaragua,(A),34,138,66,109,90,112,95,123,...,197,203,205,208,210,212,214,217,218,220
45,Nigeria,(R),28,36,36,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
46,Panama,(A),63,67,67,67,77,77,77,81,...,67,67,67,67,67,67,67,67,67,67
47,Sierra Leone,(R),9,9,9,5,5,8,8,5,...,5,5,5,5,5,5,5,5,5,5
48,Sri Lanka,(R/A),67,67,28,20,20,20,20,20,...,30,35,35,35,35,35,35,35,35,35
49,Thailand,(R/A),188,220,233,250,283,417,333,390,...,700,775,"1,100","1,130","1,200","1,250","1,300","1,350","1,375","1,400"
50,Togo,(R),1,1,1,1,1,1,1,1,...,2,2,0,0,0,0,0,0,0,0
51,Trinidad & Tobago,(R),8,12,10,10,14,14,14,14,...,11,10,10,10,10,10,10,10,10,10
52,Uganda,(R/A),70,75,75,75,80,80,80,101,...,189,204,210,216,221,229,234,240,245,250
53,Venezuela,(A),782,815,850,886,923,962,"1,003","1,046",...,"1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,600","1,550"
54,Viet Nam,(R/A),150,230,250,267,267,282,298,314,...,"1,208","1,583","1,650","1,825","2,000","2,200","2,300","2,400","2,500","2,700"
55,Yemen,(A),0,0,0,0,0,0,0,0,...,130,130,130,130,130,125,115,100,90,65

In [8]:
new_dc_df = new_dc_df.rename(columns = {"Crop year": "Producer"})
new_dc_df.head()

2,Producer,NaN,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19
5,Angola,(R/A),20,30,35,20,25,10,20,40,...,30,30,30,30,30,30,30,30,30,30
6,Bolivia (Plurinational State of),(A),25,27,28,29,30,31,32,33,...,46,48,49,51,52,54,55,57,59,60
7,Brazil,(A/R),"8,200","8,500","8,900","9,100","9,300","10,100","11,000","11,500",...,"18,390","19,132","19,720","20,330","20,085","20,333","20,508","21,225","21,997","22,250"
8,Burundi,(A/R),2,2,2,2,2,2,2,2,...,1,2,2,2,2,2,2,2,2,2
9,Ecuador,(A/R),350,350,350,350,350,350,300,300,...,150,150,150,150,155,155,155,155,155,155

In [9]:
new_dc_df.set_index(keys="Producer")
new_dc_df

2,Producer,NaN,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19
5,Angola,(R/A),20,30,35,20,25,10,20,40,...,30,30,30,30,30,30,30,30,30,30
6,Bolivia (Plurinational State of),(A),25,27,28,29,30,31,32,33,...,46,48,49,51,52,54,55,57,59,60
7,Brazil,(A/R),"8,200","8,500","8,900","9,100","9,300","10,100","11,000","11,500",...,"18,390","19,132","19,720","20,330","20,085","20,333","20,508","21,225","21,997","22,250"
8,Burundi,(A/R),2,2,2,2,2,2,2,2,...,1,2,2,2,2,2,2,2,2,2
9,Ecuador,(A/R),350,350,350,350,350,350,300,300,...,150,150,150,150,155,155,155,155,155,155
10,Indonesia,(R/A),"1,242","1,280","1,319","1,359","1,400","1,443","1,486","1,532",...,"3,333","3,333","3,667","3,900","4,250","4,417","4,550","4,650","4,750","4,800"
11,Madagascar,(R),350,300,350,360,167,167,167,167,...,467,467,450,430,410,390,370,360,365,375
12,Malawi,(A),2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
13,Papua New Guinea,(A/R),3,3,3,2,2,2,2,2,...,2,1,1,2,2,2,2,2,2,2
14,Paraguay,(A),15,15,15,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
15,Peru,(A),190,190,200,200,200,200,200,200,...,250,250,250,250,250,250,250,250,250,250
16,Rwanda,(A),1,1,1,1,1,1,1,3,...,1,1,1,1,1,1,1,1,1,1
17,Timor-Leste,(A),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,Zimbabwe,(A),8,8,8,8,8,7,4,4,...,4,4,4,4,4,4,4,4,4,4
21,Congo,(R),3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
22,Cuba,(A),213,213,195,194,194,194,189,195,...,220,220,220,220,220,220,220,220,220,220
23,Dominican Republic,(A/R),320,320,320,320,330,350,325,325,...,378,378,378,378,383,388,388,390,390,390
24,Haiti,(A),220,330,330,330,330,330,330,330,...,340,340,340,340,340,340,340,340,340,345
25,Philippines,(R/A),720,750,750,770,790,810,831,853,...,"1,820","2,125","2,175","2,325","2,550","2,800","3,000","3,030","3,180","3,300"
26,Tanzania,(A/R),4,4,19,18,18,14,17,17,...,47,47,59,72,73,77,92,91,92,92
27,Zambia,(A),2,2,1,1,2,1,1,1,...,0,0,0,0,0,0,0,0,0,0
30,Benin,(R),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,Cameroon,(R/A),83,83,83,100,100,100,100,100,...,69,68,70,72,73,75,76,77,78,78
32,Central African Republic,(R),28,28,28,25,15,10,10,10,...,8,10,13,17,20,20,20,20,20,20
33,Colombia,(A),"1,235","1,269","1,303","1,339","1,375","1,359","1,343","1,328",...,"1,274","1,311","1,435","1,514","1,617","1,665","1,720","1,736","1,793","1,791"
34,Costa Rica,(A),375,375,375,375,375,375,375,375,...,295,407,381,423,335,381,449,329,353,365
35,CÃ´te d'Ivoire,(R),50,50,50,50,50,50,50,50,...,317,317,317,317,317,317,317,317,317,317
36,Democratic Republic of Congo,(R/A),200,200,200,200,200,200,200,200,...,200,200,200,200,200,200,200,200,200,200
37,El Salvador,(A),180,180,230,230,230,270,230,192,...,268,276,273,277,275,280,285,292,300,300
38,Equatorial Guinea,(R),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,Ethiopia,(A),"1,200","1,264","1,331","1,402","1,476","1,555","1,637","1,724",...,"3,210","3,383","3,383","3,400","3,550","3,625","3,700","3,725","3,750","3,800"
40,Gabon,(R),2,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
41,Ghana,(R),17,17,17,17,28,28,3,3,...,2,2,2,2,2,2,2,2,2,2
42,Guatemala,(A/R),300,300,300,310,310,310,300,300,...,320,340,350,360,370,380,390,390,395,395
43,Guinea,(R),25,25,63,33,50,50,50,50,...,50,50,50,50,50,50,50,50,50,50
44,Guyana,(R),0,0,0,0,0,0,0,0,...,8,9,9,9,9,9,9,9,9,9
45,Honduras,(A),188,257,240,230,253,161,168,161,...,307,335,340,345,350,355,365,370,375,375
46,India,(R/A),903,917,917,833,835,837,838,839,...,"1,325","1,325","1,325","1,375","1,400","1,430","1,450","1,440","1,470","1,475"
47,Jamaica,(A),7,11,6,10,15,15,18,20,...,9,9,9,9,9,9,9,9,9,9
48,Kenya,(A),50,50,50,50,50,50,50,50,...,50,50,50,50,55,55,60,60,65,70
49,Lao People's Democratic Republic,(R),0,0,0,0,0,0,0,0,...,150,150,150,150,150,150,150,150,155,155
50,Liberia,(R),3,3,3,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
51,Mexico,(A/R),"1,374","1,200","1,300","1,070","1,020","1,179","1,235","1,201",...,"2,200","2,354","2,354","2,354","2,321","2,347","2,329","2,360","2,400","2,450"
52,Nepal,(A),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53,Nicaragua,(A),34,138,66,109,90,112,95,123,...,197,203,205,208,210,212,214,217,218,220
54,Nigeria,(R),28,36,36,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
55,Panama,(A),63,67,67,67,77,77,77,81,...,67,67,67,67,67,67,67,67,67,67
56,Sierra Leone,(R),9,9,9,5,5,8,8,5,...,5,5,5,5,5,5,5,5,5,5
57,Sri Lanka,(R/A),67,67,28,20,20,20,20,20,...,30,35,35,35,35,35,35,35,35,35
58,Thailand,(R/A),188,220,233,250,283,417,333,390,...,700,775,"1,100","1,130","1,200","1,250","1,300","1,350","1,375","1,400"
59,Togo,(R),1,1,1,1,1,1,1,1,...,2,2,0,0,0,0,0,0,0,0
60,Trinidad & Tobago,(R),8,12,10,10,14,14,14,14,...,11,10,10,10,10,10,10,10,10,10
61,Uganda,(R/A),70,75,75,75,80,80,80,101,...,189,204,210,216,221,229,234,240,245,250
62,Venezuela,(A),782,815,850,886,923,962,"1,003","1,046",...,"1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,600","1,550"
63,Viet Nam,(R/A),150,230,250,267,267,282,298,314,...,"1,208","1,583","1,650","1,825","2,000","2,200","2,300","2,400","2,500","2,700"
64,Yemen,(A),0,0,0,0,0,0,0,0,...,130,130,130,130,130,125,115,100,90,65

In [10]:
final_df = new_dc_df.drop(new_dc_df.columns[[1]], axis=1)
final_df

2,Producer,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,1998/99,...,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19
5,Angola,20,30,35,20,25,10,20,40,30,...,30,30,30,30,30,30,30,30,30,30
6,Bolivia (Plurinational State of),25,27,28,29,30,31,32,33,33,...,46,48,49,51,52,54,55,57,59,60
7,Brazil,"8,200","8,500","8,900","9,100","9,300","10,100","11,000","11,500","12,200",...,"18,390","19,132","19,720","20,330","20,085","20,333","20,508","21,225","21,997","22,250"
8,Burundi,2,2,2,2,2,2,2,2,2,...,1,2,2,2,2,2,2,2,2,2
9,Ecuador,350,350,350,350,350,350,300,300,300,...,150,150,150,150,155,155,155,155,155,155
10,Indonesia,"1,242","1,280","1,319","1,359","1,400","1,443","1,486","1,532","1,578",...,"3,333","3,333","3,667","3,900","4,250","4,417","4,550","4,650","4,750","4,800"
11,Madagascar,350,300,350,360,167,167,167,167,167,...,467,467,450,430,410,390,370,360,365,375
12,Malawi,2,2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
13,Papua New Guinea,3,3,3,2,2,2,2,2,1,...,2,1,1,2,2,2,2,2,2,2
14,Paraguay,15,15,15,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
15,Peru,190,190,200,200,200,200,200,200,200,...,250,250,250,250,250,250,250,250,250,250
16,Rwanda,1,1,1,1,1,1,1,3,3,...,1,1,1,1,1,1,1,1,1,1
17,Timor-Leste,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,Zimbabwe,8,8,8,8,8,7,4,4,4,...,4,4,4,4,4,4,4,4,4,4
21,Congo,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
22,Cuba,213,213,195,194,194,194,189,195,200,...,220,220,220,220,220,220,220,220,220,220
23,Dominican Republic,320,320,320,320,330,350,325,325,325,...,378,378,378,378,383,388,388,390,390,390
24,Haiti,220,330,330,330,330,330,330,330,330,...,340,340,340,340,340,340,340,340,340,345
25,Philippines,720,750,750,770,790,810,831,853,810,...,"1,820","2,125","2,175","2,325","2,550","2,800","3,000","3,030","3,180","3,300"
26,Tanzania,4,4,19,18,18,14,17,17,17,...,47,47,59,72,73,77,92,91,92,92
27,Zambia,2,2,1,1,2,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
30,Benin,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,Cameroon,83,83,83,100,100,100,100,100,100,...,69,68,70,72,73,75,76,77,78,78
32,Central African Republic,28,28,28,25,15,10,10,10,19,...,8,10,13,17,20,20,20,20,20,20
33,Colombia,"1,235","1,269","1,303","1,339","1,375","1,359","1,343","1,328","1,312",...,"1,274","1,311","1,435","1,514","1,617","1,665","1,720","1,736","1,793","1,791"
34,Costa Rica,375,375,375,375,375,375,375,375,375,...,295,407,381,423,335,381,449,329,353,365
35,CÃ´te d'Ivoire,50,50,50,50,50,50,50,50,50,...,317,317,317,317,317,317,317,317,317,317
36,Democratic Republic of Congo,200,200,200,200,200,200,200,200,200,...,200,200,200,200,200,200,200,200,200,200
37,El Salvador,180,180,230,230,230,270,230,192,192,...,268,276,273,277,275,280,285,292,300,300
38,Equatorial Guinea,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,Ethiopia,"1,200","1,264","1,331","1,402","1,476","1,555","1,637","1,724","1,816",...,"3,210","3,383","3,383","3,400","3,550","3,625","3,700","3,725","3,750","3,800"
40,Gabon,2,1,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
41,Ghana,17,17,17,17,28,28,3,3,1,...,2,2,2,2,2,2,2,2,2,2
42,Guatemala,300,300,300,310,310,310,300,300,300,...,320,340,350,360,370,380,390,390,395,395
43,Guinea,25,25,63,33,50,50,50,50,50,...,50,50,50,50,50,50,50,50,50,50
44,Guyana,0,0,0,0,0,0,0,0,5,...,8,9,9,9,9,9,9,9,9,9
45,Honduras,188,257,240,230,253,161,168,161,138,...,307,335,340,345,350,355,365,370,375,375
46,India,903,917,917,833,835,837,838,839,900,...,"1,325","1,325","1,325","1,375","1,400","1,430","1,450","1,440","1,470","1,475"
47,Jamaica,7,11,6,10,15,15,18,20,15,...,9,9,9,9,9,9,9,9,9,9
48,Kenya,50,50,50,50,50,50,50,50,50,...,50,50,50,50,55,55,60,60,65,70
49,Lao People's Democratic Republic,0,0,0,0,0,0,0,0,0,...,150,150,150,150,150,150,150,150,155,155
50,Liberia,3,3,3,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
51,Mexico,"1,374","1,200","1,300","1,070","1,020","1,179","1,235","1,201","1,108",...,"2,200","2,354","2,354","2,354","2,321","2,347","2,329","2,360","2,400","2,450"
52,Nepal,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53,Nicaragua,34,138,66,109,90,112,95,123,127,...,197,203,205,208,210,212,214,217,218,220
54,Nigeria,28,36,36,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
55,Panama,63,67,67,67,77,77,77,81,67,...,67,67,67,67,67,67,67,67,67,67
56,Sierra Leone,9,9,9,5,5,8,8,5,5,...,5,5,5,5,5,5,5,5,5,5
57,Sri Lanka,67,67,28,20,20,20,20,20,30,...,30,35,35,35,35,35,35,35,35,35
58,Thailand,188,220,233,250,283,417,333,390,433,...,700,775,"1,100","1,130","1,200","1,250","1,300","1,350","1,375","1,400"
59,Togo,1,1,1,1,1,1,1,1,2,...,2,2,0,0,0,0,0,0,0,0
60,Trinidad & Tobago,8,12,10,10,14,14,14,14,14,...,11,10,10,10,10,10,10,10,10,10
61,Uganda,70,75,75,75,80,80,80,101,116,...,189,204,210,216,221,229,234,240,245,250
62,Venezuela,782,815,850,886,923,962,"1,003","1,046","1,090",...,"1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,600","1,550"
63,Viet Nam,150,230,250,267,267,282,298,314,332,...,"1,208","1,583","1,650","1,825","2,000","2,200","2,300","2,400","2,500","2,700"
64,Yemen,0,0,0,0,0,0,0,0,0,...,130,130,130,130,130,125,115,100,90,65

In [11]:
final_df.set_index(keys="Producer")

2,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,1998/99,1999/00,...,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19
Producer,,,,,,,,,,,,,,,,,,,,,
Angola,20,30,35,20,25,10,20,40,30,20,...,30,30,30,30,30,30,30,30,30,30
Bolivia (Plurinational State of),25,27,28,29,30,31,32,33,33,34,...,46,48,49,51,52,54,55,57,59,60
Brazil,"8,200","8,500","8,900","9,100","9,300","10,100","11,000","11,500","12,200","12,700",...,"18,390","19,132","19,720","20,330","20,085","20,333","20,508","21,225","21,997","22,250"
Burundi,2,2,2,2,2,2,2,2,2,2,...,1,2,2,2,2,2,2,2,2,2
Ecuador,350,350,350,350,350,350,300,300,300,230,...,150,150,150,150,155,155,155,155,155,155
Indonesia,"1,242","1,280","1,319","1,359","1,400","1,443","1,486","1,532","1,578","1,626",...,"3,333","3,333","3,667","3,900","4,250","4,417","4,550","4,650","4,750","4,800"
Madagascar,350,300,350,360,167,167,167,167,167,56,...,467,467,450,430,410,390,370,360,365,375
Malawi,2,2,2,2,2,2,2,2,2,1,...,1,1,1,1,1,1,1,1,1,1
Papua New Guinea,3,3,3,2,2,2,2,2,1,2,...,2,1,1,2,2,2,2,2,2,2
Paraguay,15,15,15,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
Peru,190,190,200,200,200,200,200,200,200,200,...,250,250,250,250,250,250,250,250,250,250
Rwanda,1,1,1,1,1,1,1,3,3,2,...,1,1,1,1,1,1,1,1,1,1
Timor-Leste,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zimbabwe,8,8,8,8,8,7,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Congo,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
Cuba,213,213,195,194,194,194,189,195,200,200,...,220,220,220,220,220,220,220,220,220,220
Dominican Republic,320,320,320,320,330,350,325,325,325,325,...,378,378,378,378,383,388,388,390,390,390
Haiti,220,330,330,330,330,330,330,330,330,340,...,340,340,340,340,340,340,340,340,340,345
Philippines,720,750,750,770,790,810,831,853,810,862,...,"1,820","2,125","2,175","2,325","2,550","2,800","3,000","3,030","3,180","3,300"
Tanzania,4,4,19,18,18,14,17,17,17,14,...,47,47,59,72,73,77,92,91,92,92
Zambia,2,2,1,1,2,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
Benin,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cameroon,83,83,83,100,100,100,100,100,100,100,...,69,68,70,72,73,75,76,77,78,78
Central African Republic,28,28,28,25,15,10,10,10,19,21,...,8,10,13,17,20,20,20,20,20,20
Colombia,"1,235","1,269","1,303","1,339","1,375","1,359","1,343","1,328","1,312","1,297",...,"1,274","1,311","1,435","1,514","1,617","1,665","1,720","1,736","1,793","1,791"
Costa Rica,375,375,375,375,375,375,375,375,375,375,...,295,407,381,423,335,381,449,329,353,365
CÃ´te d'Ivoire,50,50,50,50,50,50,50,50,50,50,...,317,317,317,317,317,317,317,317,317,317
Democratic Republic of Congo,200,200,200,200,200,200,200,200,200,200,...,200,200,200,200,200,200,200,200,200,200
El Salvador,180,180,230,230,230,270,230,192,192,153,...,268,276,273,277,275,280,285,292,300,300
Equatorial Guinea,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ethiopia,"1,200","1,264","1,331","1,402","1,476","1,555","1,637","1,724","1,816","1,912",...,"3,210","3,383","3,383","3,400","3,550","3,625","3,700","3,725","3,750","3,800"
Gabon,2,1,1,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
Ghana,17,17,17,17,28,28,3,3,1,1,...,2,2,2,2,2,2,2,2,2,2
Guatemala,300,300,300,310,310,310,300,300,300,300,...,320,340,350,360,370,380,390,390,395,395
Guinea,25,25,63,33,50,50,50,50,50,50,...,50,50,50,50,50,50,50,50,50,50
Guyana,0,0,0,0,0,0,0,0,5,4,...,8,9,9,9,9,9,9,9,9,9
Honduras,188,257,240,230,253,161,168,161,138,168,...,307,335,340,345,350,355,365,370,375,375
India,903,917,917,833,835,837,838,839,900,925,...,"1,325","1,325","1,325","1,375","1,400","1,430","1,450","1,440","1,470","1,475"
Jamaica,7,11,6,10,15,15,18,20,15,11,...,9,9,9,9,9,9,9,9,9,9
Kenya,50,50,50,50,50,50,50,50,50,50,...,50,50,50,50,55,55,60,60,65,70
Lao People's Democratic Republic,0,0,0,0,0,0,0,0,0,0,...,150,150,150,150,150,150,150,150,155,155
Liberia,3,3,3,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
Mexico,"1,374","1,200","1,300","1,070","1,020","1,179","1,235","1,201","1,108","1,150",...,"2,200","2,354","2,354","2,354","2,321","2,347","2,329","2,360","2,400","2,450"
Nepal,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Nicaragua,34,138,66,109,90,112,95,123,127,130,...,197,203,205,208,210,212,214,217,218,220
Nigeria,28,36,36,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
Panama,63,67,67,67,77,77,77,81,67,67,...,67,67,67,67,67,67,67,67,67,67
Sierra Leone,9,9,9,5,5,8,8,5,5,5,...,5,5,5,5,5,5,5,5,5,5
Sri Lanka,67,67,28,20,20,20,20,20,30,30,...,30,35,35,35,35,35,35,35,35,35
Thailand,188,220,233,250,283,417,333,390,433,433,...,700,775,"1,100","1,130","1,200","1,250","1,300","1,350","1,375","1,400"
Togo,1,1,1,1,1,1,1,1,2,2,...,2,2,0,0,0,0,0,0,0,0
Trinidad & Tobago,8,12,10,10,14,14,14,14,14,14,...,11,10,10,10,10,10,10,10,10,10
Uganda,70,75,75,75,80,80,80,101,116,119,...,189,204,210,216,221,229,234,240,245,250
Venezuela,782,815,850,886,923,962,"1,003","1,046","1,090","1,136",...,"1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,650","1,600","1,550"
Viet Nam,150,230,250,267,267,282,298,314,332,350,...,"1,208","1,583","1,650","1,825","2,000","2,200","2,300","2,400","2,500","2,700"
Yemen,0,0,0,0,0,0,0,0,0,0,...,130,130,130,130,130,125,115,100,90,65

In [12]:
final_df.to_csv("domestic_consumption_ico_clean.csv", header=True)